---
# Variable                            Description                                                                           Default Value
# force_run_all                       Force all roles in the collection to run                                              false
# interface_delete_mode               Remove interface state as part of the remove role                                     false
# inventory_delete_mode               Remove inventory state as part of the remove role                                     false
# link_fabric_delete_mode             Remove fabric link state as part of the remove role                                   false
# link_vpc_delete_mode                Remove vpc link state as part of the remove role                                      false
# network_delete_mode                 Remove network state as part of the remove role                                       false
# policy_delete_mode                  Remove policy state as part of the remove role                                        false
# vrf_delete_mode                     Remove vrf state as part of the remove role                                           false
# vpc_delete_mode                     Remove vpc pair state as part of the remove role                                      false
# multisite_child_fabric_delete_mode  Remove child fabric from MSD/MFD fabric as part of the remove role                    false
# multisite_network_delete_mode       Remove network state as part of the remove role for multisite (MSD and MFD) fabrics   false
# multisite_vrf_delete_mode           Remove vrf state as part of the remove role for multisite (MSD and MFD) fabrics       false

# Parameter to ignore diff-run
force_run_all: false

# Control Parameters for 'Remove' role tasks in VXLAN EVPN, External, and ISN fabrics
interface_delete_mode: false
inventory_delete_mode: false
link_fabric_delete_mode: false
link_vpc_delete_mode: false
network_delete_mode: false
policy_delete_mode: false
vpc_delete_mode: false
vrf_delete_mode: false

# Control Parameters for 'Remove' role tasks in Multisite fabric
multisite_child_fabric_delete_mode: false
multisite_network_delete_mode: false
multisite_vrf_delete_mode: false

